### ISSUE TITLE
Ability to control/increase the Heading levels suppported by TOC Plugin

### ISSUE THREAD

**Issue by dvdmtw98** [cotes2020/jekyll-theme-chirpy#1023]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the request is based on the latest code in the `master` branch.

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Is your feature request related to a problem? Please describe

The new TOC plugin (tocbot) that has been introduced in Chirpy only works for H2 and H3. In all my articles I only use heading levels H3 and below become of which Chirpy does not show H4, H5 headers as part of the Table of Content.

## Describe the solution you'd like

If the TOC plugin has been limited to H2 and H3 because of performance reasons it would be great if an option in the config file was introduced where we can mention which levels of Headers should be considered for generating the TOC.

## Additional context

Other Issues related to TOC plugin: #1013

**Comment by v4vong** [comment]
Vote +1

**Comment by cotes2020** [comment]
The reason why the TOC only displays h2 ~ h3 headings is not due to performance, but rather to consider the horizontal width of multi-level headings.

If three levels (h2 ~ h4) are displayed, the text of the third level (h4) heading will wrap multiple times. I think this is also the reason why mainstream web design only displays h2 to h3.

**Comment by v4vong** [comment]
> The reason why the TOC only displays h2 ~ h3 headings is not due to performance, but rather to consider the horizontal width of multi-level headings.
> 
> If three levels (h2 ~ h4) are displayed, the text of the third level (h4) heading will wrap multiple times. I think this is also the reason why mainstream web design only displays h2 to h3.

But I think many guys would want to show `h4` in TOC if they want to write a very long blog post with a complex structure. So the best solution may be to make it optional.

**Comment by dvdmtw98** [comment]
> The reason why the TOC only displays h2 ~ h3 headings is not due to performance, but rather to consider the horizontal width of multi-level headings.
> 
> If three levels (h2 ~ h4) are displayed, the text of the third level (h4) heading will wrap multiple times. I think this is also the reason why mainstream web design only displays h2 to h3.

I also still feel like at least the option to show `h4` should be added so who needs it can enable it. 
I remember seeing the `h4` headers showing up in the previous TOC plugin that was used in Chirpy. Did not notice any width related issues either.

**Comment by NichtsHsu** [comment]
> If three levels (h2 ~ h4) are displayed, the text of the third level (h4) heading will wrap multiple times.

If this is the problem, I think `text-overflow: ellipsis` can be a solution.

**Comment by JoaoF17** [comment]
In my case TOC is not displaying on my posts even for h2 and h3 even though I have TOC set to true in _config.yml.  Has anyone had this issue before?

**Comment by otzslayer** [comment]
I've been modifying it myself so that H4 appears in the ToC, but I'm not sure if there's a problem. 

https://github.com/otzslayer/otzslayer.github.io/commit/2128083b857df302ffab55494c9312213656ff40

This is the commit I pushed to use, and it looks fine on my blog at the moment.

https://otzslayer.github.io/cs224w/2023/06/16/cs224w-05.html#%EC%A0%84%ED%86%B5%EC%A0%81%EC%9D%B8-gnn-%EB%A0%88%EC%9D%B4%EC%96%B4-1-gcn
