### ISSUE TITLE
Custom domain removed

### ISSUE THREAD

**Issue by gudszent** [cotes2020/jekyll-theme-chirpy#108]
## Checklist

- [x ] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x ] There are no similar reports on existing issues (including closed ones).
- [x ] I found the bug on the latest code of `master` branch.

## Describe the bug
I would like to run it under Github Pages with custom domain. When I commit any changes, the github action run as expected, but always remove the custom domain, so go back to xy.github.io
In _custom-yml I edited the url part and dont use the baseurl based the tutorial.

**Comment by cotes2020** [comment]
>In _custom-yml I edited the url...

What is `_custom-yml`? Do you mean `_config.yml`? BTW, when submitting an issue, please be careful not to submit worthless information.

The GitHub Action workflow does not have this "bug". The key to the problem is that you have not configured the custom domain name correctly. See <https://docs.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site>

**Comment by andrewlo1011** [comment]
Hi Cotes,
I also encountered similar issue. 
After associate a custom domain in the Github Pages, it will generate a file called "CNAME " in the repository. 

When we push changes to the master branch, github action will build and deploy to the gh-pages branch and it removes the "CNAME" file in the gh-pages branch.

I need to associate the custom domain again in the Github Pages setting to workaround the issue.

**Comment by cotes2020** [comment]
@andrewlo1011 add a CNAME file in your `master` branch. As the docs has explained, the `gh-pages` branch holds the build output files.

**Comment by andrewlo1011** [comment]
Hi Cotes,
Add a CNAME file in the master branch resolves the issue.  Many thanks.
