### ISSUE TITLE
Jekyll-Chirpy math does not show up in preview

### ISSUE THREAD

**Issue by preemptible** [cotes2020/jekyll-theme-chirpy#1140]
The math parses great for me while in post, yet the preview shows $\LaTeX$ commands only, see: ![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/138821092/8ae60a4c-9194-46e2-9ec0-af76e0bdb046)

**Comment by otzslayer** [comment]
Probably because the main page doesn't have "math mode" turned on.  
So I added the MathJax script to `_layouts/default.html`.

https://github.com/otzslayer/otzslayer.github.io/blob/master/_includes/mathjax_support.html  
https://github.com/otzslayer/otzslayer.github.io/blob/master/_layouts/default.html#L21

**Comment by tungsten106** [comment]
> Probably because the main page doesn't have "math mode" turned on. So I added the MathJax script to `_layouts/default.html`.
> 
> https://github.com/otzslayer/otzslayer.github.io/blob/master/_includes/mathjax_support.html https://github.com/otzslayer/otzslayer.github.io/blob/master/_layouts/default.html#L21

Thanks so much it helped with my latex fonts!!

**Comment by kapilsh** [comment]
I know this issue is closed but I suffered the same issue. The easiest way to enable it is to use `math: true` top config yaml config. Hope this is useful for others hitting the issue. 

```
---
title: ...
...
math: true
---
```
