### ISSUE TITLE
Did you rewrite all of your commits? 

### ISSUE THREAD

**Issue by mattpopovich** [cotes2020/jekyll-theme-chirpy#141]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I previously contributed to this repository, see #69. I am now attempting to merge in cotes2020/jekyll-theme-chirpy to mattpopovich/jekyll-theme-chirpy to get my fork up to date. However, when I attempt to do this, git tells me that the two repositories have unrelated histories... which doesn't make sense because I forked your repository to get mine: 
```
$ git remote -v 
origin	git@github.com:mattpopovich/jekyll-theme-chirpy.git (fetch)
origin	git@github.com:mattpopovich/jekyll-theme-chirpy.git (push)
upstream	git@github.com:cotes2020/jekyll-theme-chirpy.git (fetch)
upstream	git@github.com:cotes2020/jekyll-theme-chirpy.git (push)
$ git merge upstream/master
fatal: refusing to merge unrelated histories
```

Looking at the first commits in both of our repositories, they have different hashes: 
```
$ git log | tail 
commit c9a35c014cf9f26421c98f1651ef36953635e57d
Author: Cotes Chung <11371340+cotes2020@users.noreply.github.com>
Date:   Mon Sep 30 20:32:24 2019 +0800

    Initial import
    
    Purifying old commits.
$ git checkout upstream/master
Note: switching to 'upstream/master'.

$ git log | tail 
commit 883857365d527980c687b0742d2272aabd401981
Author: Cotes Chung <11371340+cotes2020@users.noreply.github.com>
Date:   Mon Sep 30 20:32:24 2019 +0800

    Initial import
    
    Purifying old commits.
```
Note that the commit hashes are different, [c9a35c0](https://github.com/mattpopovich/jekyll-theme-chirpy/commit/c9a35c014cf9f26421c98f1651ef36953635e57d) vs [8838573](https://github.com/cotes2020/jekyll-theme-chirpy/commit/883857365d527980c687b0742d2272aabd401981). 

So it appears that you completely rewrote all of your commits, possibly [via](https://stackoverflow.com/a/51850182/4368898) `git filter-branch filters -- --all` or similar. If so, did you do this on purpose? What was the reason? If not, just wanted to alert you of it and to advise you not to do it again. I will make a new fork of your branch so that they can be in sync again. 

Thanks again for your work thus far,

Matt

**Comment by cotes2020** [comment]
Yeah, in order to enable email privacy on GitHub, I rewritten all the history on Sep 17, 2020 and modified the email information in the `commits` I submitted.

When deciding to rewrite the commit history, I also considered the negative impact on other fork repos, but at present, this repo is not mainly for secondary development, so I took the risk to modify the history. There will be no rewriting in the future, you have my word :)

**Comment by mattpopovich** [comment]
Ah! Great answer! I knew there had to be a reason. Thanks for the explanation!

**Comment by bcaddy** [comment]
I've been trying to update my blog to a more recent version of Chirpy and can't do the standard fork syncing methods because of this. Is there an easy way for me to update/rebase to the most recent version?

**Comment by mattpopovich** [comment]
@bcaddy I only had a few changes at the time so I just started from scratch with the rewritten history and appended my changes. Unfortunately, I'm not much help. Looks like @cotes2020 responded to [your issue](https://github.com/cotes2020/jekyll-theme-chirpy/issues/290), hope you got it figured out!

**Comment by bcaddy** [comment]
Yeah, I ended up just setting everything up again. It was kind of a mess since I had a decent amount of content and had tweaked the CSS a bit. Thanks

**Comment by mattpopovich** [comment]
For anyone curious/confused, it looks like @cotes2020 rewrote 99% of the history again, back to the 4th commit. 

Previously, it was:
```
commit 611a072ddbeca5634d43464439c92520533e3bd2 (HEAD)
Author: Cotes Chung <11371340+cotes2020@users.noreply.github.com>
Date:   Mon Sep 30 20:38:41 2019 +0800

    Import the framework.
```

Now it is:
```
commit b845c829f6eab054b4f6ddd4eff7a803e071b409 (HEAD)
Author: Cotes Chung <11371340+cotes2020@users.noreply.github.com>
Date:   Mon Sep 30 20:38:41 2019 +0800

    Import the framework.
```

Notice the hashes are different. I don't know when exactly this happened but it was sometime between April 10, 2021 and November 22, 2022. 

I was trying to update my fork from v3.3.2 to v5.3.2 and saw there were about 1000 new commits and I believe this is why.

**Comment by NichtsHsu** [comment]
Actually it was Oct 24, 2021, I raised #435 on that day.

**Comment by cotes2020** [comment]
I rewrote the history within a day or two after 21/10/2021, with the purpose of removing several 0-byte files in the commit history, such as `.nojekyll` and `__init__.py` etc.

Because GitHub will store these 0-byte files in LFS on the server (even if this repo has never been configured with LFS), and occupy dozens of KB of LFS storage space in the server side. To make matters worse, these storage usage can be counted on the root of the repository network, consuming 96% of LFS free storage quota. 
![lfs-quota](https://user-images.githubusercontent.com/11371340/206872216-43dafcc3-f2ac-4bad-b977-71559f584c9a.png)

So I had to do a second massive commit history rewrite to get rid of these pointless quota consumption, and I apologize for any inconvenience caused.

For merging upstream branch:

- If you want to keep your own commit history, you can directly merge the latest upstream, and then resolve file conflicts.
- If you are worried about similar problems happening again[^rewrite], you can also consider using Chirpy-Starter.

[^rewrite]: In order to reduce invalid or wrong commits, the latest few commits of the `master` branch are sometimes rewritten (force push), but the `production` branch is stable. If you want to fork to get updates, set the upstream branch to [`production`](https://github.com/cotes2020/jekyll-theme-chirpy/tree/production) branch.
