### ISSUE TITLE
"Next" and "Previous" buttons

### ISSUE THREAD

**Issue by SajjadAlipour2006** [cotes2020/jekyll-theme-chirpy#1545]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

It is unclear that by what order are the posts meant to be read

### Describe the solution you'd like

I would like to have a "Next" and a "Previous" button at the bottom of my posts
Like many of the documentations out there
Some examples:
https://docs.djangoproject.com/
https://docs.pyrogram.org/
https://www.w3schools.com/html/default.asp

### Describe alternatives you've considered

The "NEWER" and "OLDER" buttons at the bottom of the posts aren't really helpful sometimes
The date of the posts isn't always the same as the order you should read them by
Besides, "NEWER" doesn't really imply that this is the next post you should read
And users seem to ignore them as they are lower than the "Further Reading" section
The ability to edit them may be a good solution to this

### Additional context

Here is my website: https://balethon.ir
As you can see I have countless posts for teaching the library I've created (And there is going to be even more of them)
But as you yourself may have noticed, someone who enters the website will get confused and doesn't know where to start or by which order to read the posts
Somewhat of a Next and a Previous buttons will surely be an elegant solution to this

Also thank you for this flawless theme!

**Comment by cotes2020** [comment]
You can set up `_data/locales/{region}.yml` under your repository to meet expectations.

**Comment by kungfux** [comment]
Hi @SajjadAlipour2006 

Here are couple of suggestions on how you can try to improve user experience for this specific task.

Let's say I write tutorials for `Python` and `DotNet` topics where I publish posts for one and another in mixed order.

```
_posts
├── 2024-01-01-python1.md
├── 2024-01-02-dotnet1.md
├── 2024-01-31-dotnet2.md
├── 2024-02-01-python2.md
├── 2024-02-02-dotnet3.md
└── 2024-03-03-python3.md
```

Even though they will appear mixed on the `Home` page based on date and time when they were published, `Further Reading` works the other way. It takes into account post tags and categories into account that we can utilize. So, make sure to combine them in posts like following:

```markdown
---
title: Python - 1
date: 2024-01-01 10:48:00 +0400
last_modified_at: 2024-01-01 10:48:00 +0400
categories: [Tutorial, Python]
tags: [Python]
---
```

This has a few benefits: `Further Reading` will show posts for `Python` first. Also, it will be easy to find all posts related to `Python` tutorials from `Categories` page.

P.S. You can combine posts under separate folders to make it easier for you to manage them like follows:

```
_posts
├── python
│   ├── 2024-01-01-python1.md
│   ├── 2024-02-01-python2.md
│   └── 2024-03-03-python3.md
└── dotnet  
    ├── 2024-01-02-dotnet1.md
    ├── 2024-01-31-dotnet2.md
    └── 2024-02-02-dotnet3.md
```

I understand these suggestions do not solve your query but I hope they will be somewhat useful.

P.S. In order to make `Next` and `Previous` buttons, you have to define and manage correct order of the posts manually that sounds as complex to me as to provide links at the of the posts to next tutorial which is another possible workaround.

**Comment by SajjadAlipour2006** [comment]
Thank you very much @kungfux and @cotes2020
I just followed the same method as you said and provided the links at the end of the posts
