### ISSUE TITLE
Lack of сlear update flow to new version

### ISSUE THREAD

**Issue by a-khakimov** [cotes2020/jekyll-theme-chirpy#1601]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Hello,

I've encountered an issue with the project regarding the update process to a new version. Currently, it seems there is no clear workflow or documentation on how to properly update to a newer version of the software. Specifically, it's unclear whether the correct process involves simply pulling the changes from a new tag and resolving any conflicts that arise, or if there is another preferred method.

### Describe the solution you'd like

To improve the user experience and facilitate smoother updates, it would be immensely helpful to have a dedicated update script. This script should automate the process of fetching the latest changes from the specified new version tag, merging these changes into the current setup, and providing guidance on resolving any potential conflicts.

Having such a script would streamline the update process, reduce the likelihood of errors during manual updates, and ensure that users can easily keep their installations current with the latest developments of the project.

**Comment by kungfux** [comment]
Have you checked the [Upgrade Guide](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide)?

It says that the preferred option is to use the starter project, so all you have to worry about is which version number to use.

If you went with the fork option, then you have to deal with all the possible merge conflicts and everything like a typical development procedure. "Development" is a crucial part here, because this option means that you are developing, not just using a tool.

Typically, I would say that if you go with the starter option and just maintain the version of the gem you want to use, and avoid adding any custom logic, then you should be fine in most cases. Otherwise, you are acting like a developer and are responsible for fixing any problems that may arise. This is especially true considering that we are talking about a theme, not a core instrument.

I don't disagree with your suggestion, but I'm not sure what exactly could be done to automate development.

**Comment by lextm** [comment]
I think if you can keep a branch for all fork option users, where all necessary files have been deleted already, then such merge conflicts might be gone.

Just some rough idea, and I might be able to test and prove it.

**Comment by a-khakimov** [comment]
Absolutely, my apologies for missing that in the documentation. Thanks for the clarification; it resolves my query completely. I appreciate your patience and guidance.

**Comment by kungfux** [comment]
No worries at all @a-khakimov 
It's good to know your issue is resolved 👍
Happy coding 😊
