### ISSUE TITLE
Preview images on home page fail to render in 6.5.4

### ISSUE THREAD

**Issue by steveng57** [cotes2020/jekyll-theme-chirpy#1625]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Changes to img-url.html have broken the url generation for preview images, resulting in bad links for posts that use preview images.  All preview images on the home page fail to render.  Favicon seems to have suffered the same fate.

In 6.5.3, the img src attribute was properly generated.
`<img loading="lazy" alt="About 2 weeks to assemble" src="/assets/img/posts/assembly-table/thumbnails/20201001_193728.jpeg">`

In 6.5.4, In the image link, there are now two slashes prefixing the src attribute.
`<img loading="lazy" alt="About 2 weeks to assemble" src="//assets/img/posts/assembly-table/thumbnails/20201001_193728.jpeg">`

There were changes to the img-url.html  that look like they may have caused this.
https://github.com/cotes2020/jekyll-theme-chirpy/compare/v6.5.3...v6.5.4

Please note that all my posts use the preview image with the following format for the image declaration in the YAML front matter.
```
image:
  path: /thumbnails/20170127_010801.jpeg
  alt: MDF and 2x4's - pretty simple
img_path: /assets/img/posts/first-workbench
```

Note that I am **not** using a CDN for any images.

### Steps To Reproduce

1.  6.5.4 environment
2. Format your preview image YAML as described above in a post Front Matter
3. Run.  
Preview images do not show up on the home page.  They do show up however on the post itself.

### Expected Behavior

preview images should be visible in the home page.

### Environment

- Ruby: 3.2.1
- Jekyll: 4.3.3
- Chirpy:  6,5,4

**Comment by Santoshkurmi** [comment]
I am facing the same problem. Yesterday everything was working properly. Today I write a simple post, and once the github build the page , all the images tag stopped working on both preview images as well as any other image tag. 

The problem is if there is image path like : image: /assets/cat.jpg ,  it renders the img tag with 
<img src="//assets/cat.jpg"/>  , so it adds extras slash in place of image path for relative file path. For url images,it is working fine. If there is two slash infront of image path, the browser is treating the path as http://assets/cat.jpg which is invalid url.

For now, I have restricted in Gemfile to v6.5.3 only, now again everything is working fine.

**Comment by DmitriyFrogo** [comment]
For me, after update to 6.5.4, html-proofer give me errors like "Image link //commons/avatar.jpg is a protocol-relative URL, use explicit https:// instead" and refused to build whole site
I fixed this issue by adding "https://USERNAME.github.io" domain to img_cdn, as described here https://github.com/cotes2020/jekyll-theme-chirpy/pull/1623

**Comment by Santoshkurmi** [comment]
> For me, after update to 6.5.4, html-proofer give me errors like "Image link //commons/avatar.jpg is a protocol-relative URL, use explicit https:// instead" and refused to build whole site I fixed this issue by adding "https://USERNAME.github.io" domain to img_cdn, as described here #1623

Yours also the same double slash problem in a image relative path😴

**Comment by cotes2020** [comment]
It'll be fixed soon.

**Comment by bethanybeachbum** [comment]
I am having a very similar problem.

Steps To Reproduce
During tests, images cannot be found.

Expected Behavior
images should past testing.

Environment:
Ruby: 3.2.3
Jekyll: 4.3.3
Chirpy: 6.5.5

test error:
<img width="712" alt="Screenshot 2024-03-24 at 12 30 57 PM" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/19581195/2f658fea-6e36-4918-aa1e-190ad5823cad">

To solve problem I am referencing all pictures on my laptop this way:
![ohiopyle] (https://github.com/bethanybeachbum/bethanybeachbum.github.io/blob/main/assets/img/Ohiopyle.jpeg)
Then once tests pass, I go into my files on gitthub and rewrite accordingly:
![ohiopyle](assets/img/Ohiopyle.jpeg) 

Thanks for a great theme! I am committed to making it work.

**Comment by kungfux** [comment]
@bethanybeachbum I see no discrepancy in tests. Those images mentioned in test pipeline do not exist in your `/assets/img` folder as I can see. Please double check image names your are trying to use.

- `/assets/img/trail.jpg` does not exist, instead you have `assets/img/trail2.jpg`
- image `/assets/img/Ohiopyle.jpg` does not exist, instead you have `/assets/img/Ohiopyle.jpeg`

**Comment by bethanybeachbum** [comment]
Dear Alexander Fuchs:

I owe you two beers.
One for being so prompt in your response.
Two for pointing out my dumb syntax mistakes.

Thank you very much 
Mark Brown
