### ISSUE TITLE
Categories section having trouble accessing individual page categories

### ISSUE THREAD

**Issue by Courtneyp123** [cotes2020/jekyll-theme-chirpy#164]
Hello! I'm working with Categories, but am having trouble when I click into a specific category or post.  How should I troubleshoot this? I have made a fork under my account.  

I believe I'm having specific issues to ERROR `/categories/components/' not found, ETC. It brings me to a 404 page when I click into the components category for example. 

Thanks!

**Comment by amalshaji** [comment]
I'm having a similar issue. When run locally, all tags and categories work. But when pushed to GH, both of them returns 404

**Comment by yuliannybetancourt** [comment]
I am presenting the same problem with the categories and files, it sends me a 404.

**Comment by rudolphp** [comment]
I am also having this issue. It is because the build is not creating these pages. below errors.
`
➜  tel git:(master) bash tools/run.sh
_scripts/sh/create_pages.sh: line 28: yq: command not found
_scripts/sh/create_pages.sh: line 29: yq: command not found
_scripts/sh/create_pages.sh: line 40: yq: command not found
_scripts/sh/create_pages.sh: line 41: yq: command not found
_scripts/sh/create_pages.sh: line 28: yq: command not found
_scripts/sh/create_pages.sh: line 29: yq: command not found
_scripts/sh/create_pages.sh: line 40: yq: command not found
_scripts/sh/create_pages.sh: line 41: yq: command not found
_scripts/sh/create_pages.sh: line 28: yq: command not found
_scripts/sh/create_pages.sh: line 29: yq: command not found
_scripts/sh/create_pages.sh: line 40: yq: command not found
_scripts/sh/create_pages.sh: line 41: yq: command not found
_scripts/sh/create_pages.sh: line 28: yq: command not found
_scripts/sh/create_pages.sh: line 29: yq: command not found
_scripts/sh/create_pages.sh: line 40: yq: command not found
_scripts/sh/create_pages.sh: line 41: yq: command not found
_scripts/sh/create_pages.sh: line 28: yq: command not found
_scripts/sh/create_pages.sh: line 29: yq: command not found
_scripts/sh/create_pages.sh: line 40: yq: command not found
_scripts/sh/create_pages.sh: line 41: yq: command not found
_scripts/sh/create_pages.sh: line 28: yq: command not found
_scripts/sh/create_pages.sh: line 29: yq: command not found
_scripts/sh/create_pages.sh: line 40: yq: command not found
_scripts/sh/create_pages.sh: line 41: yq: command not found
_scripts/sh/create_pages.sh: line 28: yq: command not found
_scripts/sh/create_pages.sh: line 29: yq: command not found
_scripts/sh/create_pages.sh: line 40: yq: command not found
_scripts/sh/create_pages.sh: line 41: yq: command not found
`

**Comment by amalshaji** [comment]
@rudolphp you need to install [yq](https://github.com/mikefarah/yq)

**Comment by Courtneyp123** [comment]
@rudolphp when you install yq, are you still running into the 404 error?

**Comment by Courtneyp123** [comment]
> I'm having a similar issue. When run locally, all tags and categories work. But when pushed to GH, both of them returns 404

Hmm mine isn't even running locally for Categories.  Was your local always working from the start?

**Comment by amalshaji** [comment]
Yes, it was working from the beginning(with some troubles). Anyway, I moved to `hugo`. Jekyll is painfully slow.

**Comment by Cloufish** [comment]
I have problems regarding arguments that are passed to yq. yq can't find directory paths that are passed.
```
yq: error: argument files: can't open 'category': [Errno 2] No such file or directory: 'category'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'tags.*': [Errno 2] No such file or directory: 'tags.*'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'tag': [Errno 2] No such file or directory: 'tag'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'categories.*': [Errno 2] No such file or directory: 'categories.*'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'category': [Errno 2] No such file or directory: 'category'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'tags.*': [Errno 2] No such file or directory: 'tags.*'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'tag': [Errno 2] No such file or directory: 'tag'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'categories.*': [Errno 2] No such file or directory: 'categories.*'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          jq_filter [files [files ...]]

```

**Comment by rudolphp** [comment]
@Courtneyp123 - installing yp fixed the issue

**Comment by dev-m00n** [comment]
I have faced this issue, but not it's resolved.
I used to use docker to run locally, but it showed me 404pages for categories and tags.
But When I install ruby dependencies, and run `tools/run.sh`, it works
```bash
$> bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...

$> ./tools/run.sh
...
```
I guess there is something missing in Dockerfile

**Comment by dev-m00n** [comment]
I found out that running script is helpful
```bash
./_script/sh/create_pages.sh
```
Then it will creates tags and categories pages, then commit and push them. the pages will be showed up

**Comment by amalshaji** [comment]
yeah, you just have to run `bash tools/build.sh`. This will take care of `create_pages.sh`.

**Comment by cotes2020** [comment]
All of the answers above are wrong or incomplete. Take a few minutes to read the documentation and you guys won't be bothered by such silly mistakes.
