### ISSUE TITLE
Private Blog Posts

### ISSUE THREAD

**Issue by ExtremeKrish** [cotes2020/jekyll-theme-chirpy#1649]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Isn't there any way to upload private posts which will not be indexed in feed , but are available via link

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by kungfux** [comment]
Why would we need this? What is the use case, I wonder?

**Comment by ildoc** [comment]
Maybe I want to post something accessible only by whom I give the link to, without having it listed

Pelican has this feature

-------- Messaggio originale --------
04/04/24 21:22, Alexander Fuks  ha scritto:

**Comment by kungfux** [comment]
That's why I ask. Why should I use a blogging tool to create a hidden post? There are already mechanisms like drafts and unpublished posts that I completely understand. However, what is the purpose of hidden content in theme for Jekyll? I have nothing against your suggestion, I just found it unclear to me.
