### ISSUE TITLE
Duplicate Post Titles

### ISSUE THREAD

**Issue by zhoukenny** [cotes2020/jekyll-theme-chirpy#18]
**Repeated blog post titles allows only the most recent blog post be shown**

**To Reproduce**
1. Create a post with any date and any title, e.g. "2019-01-01-new-year.md".
2. Create a post with any date and the same title, e.g. "2020-01-09-new-year.md".
3. Run "jekyll serve"
4. See error; i.e. only your newest blog post is accessible, e.g. "http://127.0.0.1:4000/posts/new-year/" shows the post dated Jan 09, 2020.

**Expected behavior**
I should be able to see both blog posts, regardless of title. If the setup of the blog posts' URLs were `yyyy-mm-dd-title`, this problem might be avoided.

**Additional context**
Not sure if I should have posted under Bug Report - sorry if this is a repost.

**Comment by cotes2020** [comment]
Well, it's the Jekyll setting stuff: [permalinks](https://jekyllrb.com/docs/permalinks/). In this project  it was set to `/posts/:title/`, so as you do, the generated static file overrides will appear. 

I don't think it's a good idea that give two(or more) different posts with a same title, because it will confuse your readers, and even yourself. But if you insist on doing so, there‘re two methods to avoid file overwriting:
1. Change the `permalinks` in config
2. A little trick that suffix your duplicate files, e.g. '2020-01-09-new-year-**SUFFIX**.md'

**Comment by zhoukenny** [comment]
Great! Thank you for that information. Sorry for the bug ticket.
