### ISSUE TITLE
Bundle install in github actions is too long

### ISSUE THREAD

**Issue by dandanua** [cotes2020/jekyll-theme-chirpy#191]
It looks like caching doesn't work for some reason. Bundle installation takes around 4 minutes every time.

**Comment by cotes2020** [comment]
Exactly. I also noticed that, too. After investigating, I found that the some `gem` dependencies have been updated, but the cache entries of  [`actions/cache`](https://github.com/actions/cache) have not been changed after action build.

This issue can be solved by removing the invalid cache entries of `actions/cache`. Since the Github Action **does not** support manual cache deletion, to my knowlege at present, there are two ways to remove the invalid cache:

1. Modify `Gemfile` (removing a blank line, or adding comments) so that `actions/cache` will be triggered to generate the new cache.
2. Stop any push and pr, and after 7 days, the cache will automatically expire (see: [the github docs](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy))
