### ISSUE TITLE
Liquid Exception: _layouts/post.html

### ISSUE THREAD

**Issue by pipiscrew** [cotes2020/jekyll-theme-chirpy#213]
## Checklist
- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
So I deploy it fist with 1500 posts, working fine... 

Extend the time for build by adding the `timeout-minutes` property 
```
jobs:
  continuous-delivery:

    runs-on: ubuntu-latest
    timeout-minutes: 1200
```

Then add the needed **14k posts**, 
![1826](https://user-images.githubusercontent.com/3852762/102188033-7bb2f980-3ebd-11eb-8c63-55d9c624544e.png)

tried two times, the error is the same 

`/home/runner/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:39:in `instance_of?': SIGTERM (SignalException)`

![2020-12-15_100531](https://user-images.githubusercontent.com/3852762/102188070-88cfe880-3ebd-11eb-8b21-2a98fcb6073c.jpg)

@cotes2020 any tip ?

-edit-
attaching the logs
[logs_7.zip](https://github.com/cotes2020/jekyll-theme-chirpy/files/5694284/logs_7.zip)

**Comment by pipiscrew** [comment]
I put it locally to build the site, Im on 17h 44m, still going w/o error... lets see.

**Comment by cotes2020** [comment]
Did you want to stress test gh-actions or Jekyll through 14k posts?

I suspect that some of those posts caused build errors. Using the `--trace` option when Jekyll building should be able to output more debug logs, but you should not build 14k at a time, but build them one by one **locally**. Certainly, this needs to be implemented with automatic scripts. The general idea is:

1. Empty the `_posts` directory
2. Put an untested post file into it
3. Run `jekyll build --trace`
4. If successful, repeat steps 1-3, otherwise, mark the bad post and leave a log.
5. Repeat the above 4 steps for the remaining posts

**Comment by pipiscrew** [comment]
@cotes2020 no worries I defeat this^ (took ~1day to find how must be on 14.5k markdown files) more @ 
https://github.com/pipiscrew/wordpress2markdown

--

possible all the **mess**, made by **Simple-Jekyll-Search** (building **search.json**)

**Comment by pipiscrew** [comment]
![Snap2](https://user-images.githubusercontent.com/3852762/102507631-262d4700-408d-11eb-89e5-2be3e03698b5.png)

this is the build going on.. when error you getting a warning... Im posting this to acknowledge that in the beginning the mem was 2.1gb, now after 17h+ went to 3.1gb :) :)  

is a PC exclusive for **jekyll**, nothing else running.

--

In the meanwhile found (what I will try if crashed again)
https://github.com/jekyll/jekyll/pull/7928

**Comment by pipiscrew** [comment]
is alive @ 
https://pipiscrew.github.io/

;)
