### ISSUE TITLE
We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

### ISSUE THREAD

**Issue by YaoQi17** [cotes2020/jekyll-theme-chirpy#34]
```
disqus:
  comments: true  # boolean type, the global switch for posts comments.
  shortname: 'https-yaoqi17-github-io-1'    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
```
I fill this config, but disqus is unable to load. Would you give me a hand?

**Comment by YaoQi17** [comment]
Today，I found that the fucking disqus is  available！！

**Comment by sheeepdev** [comment]
I have the same issue

**Comment by sheeepdev** [comment]
Anyone?

**Comment by Iyxan23** [comment]
Got this issue too! Is there any like extra steps to do on disqus' admin panel or something?
I've put the short name and set my website URL correctly and it seemed to not work and displayed the same message "We were unable to load Disqus..."

**Comment by sheeepdev** [comment]
For me, it started working...

**Comment by Iyxan23** [comment]
Yeaaaahhh, It has just started working for me too! very weird!

**Comment by Iyxan23** [comment]
I removed the `page.url |` part of the code at the line
https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_includes/disqus.html#L19

Since at [disqus' troubleshooting page](https://help.disqus.com/en/articles/1717301-i-m-receiving-the-message-we-were-unable-to-load-disqus#incorrectly-formatted-javascript-configuration-variables), they mentioned that `this.page.url` must be an absolute URL. I changed it and disqus showed up properly

But while I was submitting a bug report, I reverted my change to include `page.url` to show a screenshot of the issue, but weirdly, it still works! what!?

**Comment by sheeepdev** [comment]
Ah! I remember now! I did this too but I changed the page URL to the absolute one, and it worked!
