### ISSUE TITLE
Cannot run site when pushed to github

### ISSUE THREAD

**Issue by nirajmaharz** [cotes2020/jekyll-theme-chirpy#353]
I can run the site locally but when i push it on github it does not work. What am i missing here.
![local](https://user-images.githubusercontent.com/25547600/123532003-05733780-d729-11eb-863b-63769f8bd9a9.PNG)

## After pushing to github
![github](https://user-images.githubusercontent.com/25547600/123532033-305d8b80-d729-11eb-8efd-792e064f01fb.PNG)

**Comment by NichtsHsu** [comment]
I checked your [repo](https://github.com/nirajmaharz/nirajmaharz.github.io), if it is the one you mentioned. 

You should set your github pages built from the `gh-pages` branch, however I cannot find such a branch on your repo. Normally, the `gh-pages` branch will be automatically updated while you push some commits to `remote/master` because of the file `.github/workflow/pages-deploy.yml`. Similarly no such a file on you repo. According to [the tutorials](https://github.com/cotes2020/jekyll-theme-chirpy#fork-on-github), you may have executed `init.sh` with the option `--no-gh`.

To make your site work, please copy the file [`.github/workflows/pages-deploy.yml.hook`](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/workflows/pages-deploy.yml.hook) to your repo and rename it to `pages-deploy.yml`. Then push some commits to `remote/master` to trigger generating the `gh-pages` branch, and set it as the source of github pages.
