### ISSUE TITLE
How to change the order of the left side navigation?

### ISSUE THREAD

**Issue by huhuni** [cotes2020/jekyll-theme-chirpy#361]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

This is my first time using Google Pages. I want to change the order of the left side navigation during the page construction process. The current order is A, and the order I want to change is B.

A: HOME - CATEGORIES - TAGS - ARCHIVES - ABOUT

B: HOME - INFORMATION(rename of ABOUT) - CATEGORIES - TAGS - ARCHIVES

Changed the about.md file of _tabs to infomation.md and changed the internal order. When running locally, it was confirmed that it was running well, but after committing, a rendering error occurred.

<img width="326" alt="스크린샷 2021-07-10 오전 3 07 19" src="https://user-images.githubusercontent.com/17395816/125119556-3ccfe400-e12c-11eb-8fab-612d67b22593.png">
<img width="333" alt="스크린샷 2021-07-10 오전 3 10 11" src="https://user-images.githubusercontent.com/17395816/125119750-7e608f00-e12c-11eb-8c7d-7bd1ea9cf05d.png">

My GitHub site : https://github.com/huhuni/huhuni.github.io
My GitHub Pages: https://huhuni.github.io

I'm not sure what I'm doing wrong. can you help me?

**Comment by huhuni** [comment]
I re-executed [action] and it works normally. In this case, should I continue to execute [action] again? Can you tell me why?

**Comment by cotes2020** [comment]
1. The method of modifying the tab order is as you described, you got it right.

2. When you push some commits to the remote repo, once the Github Action is successfully built, your website will be updated immediately, and there is no need to manually build it again. But please note that because this project uses [PWA](https://web.dev/progressive-web-apps/) technology, when you visit the updated website in the local browser, the first thing you read will be the local cache, but after about a few minutes, the PWA process automatically refreshes the cache in the background, and display the latest website content. If you want to check the latest website content immediately, you can use the incognito mode of your browser.
