### ISSUE TITLE
Suggestion to use GitHub template repositories for people that would like to use the template

### ISSUE THREAD

**Issue by p-kostic** [cotes2020/jekyll-theme-chirpy#391]
## Checklist
- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [ ] ~I was in the `master` branch of the latest code.~ n.a.

## Is your feature request related to a problem? Please describe
People who want to use the template right now are suggested to fork the project. However, doing so excludes any activity on their profile page because they're comitting to a forked repo instead of "their own". 

## Describe the solution you'd like
GitHub has a feature called [template repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository). Template repositories let users generate new repositories with the same directory structure and files. An example of a repo using this functionality can be found [here](https://github.com/sindrekjr/AdventOfCodeBase)

The repo has the template tag in the upper left corner, and a "Use this template" button

![image](https://user-images.githubusercontent.com/11349756/128347056-5b8852a9-7d83-4c3e-be8c-31d5c41e21ab.png)

## Describe alternatives you've considered

Not applicable

## Additional context

These newly created repositories will still be pointing towards your template.

![image](https://user-images.githubusercontent.com/11349756/128344124-386b006a-80f9-4736-9fad-13bf1c29813b.png)

**Comment by cotes2020** [comment]
I think you have some misunderstandings about this repo. Strictly speaking, this project is the source code of [a theme gem](https://rubygems.org/gems/jekyll-theme-chirpy), not a template. 

If you have read the content of the README, you should find that we recommend using the [Chirpy Starter](https://github.com/cotes2020/chirpy-starter) to start a new project, rather than directly fork the current repo, because the `master` branch is under development and is not stable, and the tutorial also corresponds to the lastest tag, so we don’t want people to use `master`’s content as a quick template to build their website unless they want to redevelop it.

**Comment by p-kostic** [comment]
Understandable. I may have jumped to the conclusion of "Maybe the author wasn't aware of this feature on GitHub" a bit too fast. 

However, since you're aware and have made it clear that there is a deliberate rationale, I'll refrain from raising this issue or going into detail further (e.g. Once you click 'Use this template' you can specify which branch)
