### ISSUE TITLE
I'm asking a question regarding json error.

### ISSUE THREAD

**Issue by ChanhuiSeok** [cotes2020/jekyll-theme-chirpy#45]
Hello. I'm using your theme very usefully. Thank you very much.

There seems to be a problem with my blog. 
The post **search** function does not work, so when I check the developer tools (F12 key) I get the following error message:

![error](https://user-images.githubusercontent.com/45116772/80177546-009f8900-8637-11ea-9956-73701cb6c4df.PNG)

Could you help me please? Thank you again. Have a nice day.

**Comment by cotes2020** [comment]
This issue is caused by JSON parsing errors. When generating `search.json`, the special JSON character `\` in one of your post was not processed correctly, and when `simple-jekyll-search.min.js` read this JSON file, it could not be parsed.

<img width="807" alt="Screen Shot" src="https://user-images.githubusercontent.com/11371340/80186732-10bc6600-8641-11ea-9b4b-b6213f1275ac.png">

It has now been fixed in 97e514e7928d5992a073eece8b7419cebf2365df, please merge it into your branch.

**Comment by ChanhuiSeok** [comment]
It was very helpful! I'll take a careful look at the hotfixes you post. Thank you for providing a good theme.
