### ISSUE TITLE
The website icons, texts is scattered all over the screen

### ISSUE THREAD

**Issue by magedhelmy1** [cotes2020/jekyll-theme-chirpy#46]
**Describe the bug**

When I load the website at https://magedhelmy1.github.io/web/
everything is all over the place 

**To Reproduce**
1) Fork the project
2) Go to the forked project on your github and rename the forked github. For example "webpage"
3) On the same page in settings, scroll down to "Github pages" and enable it.
4) Clone the project locally
5) Deleted .travis.yml and .github
6) Open_config.yml on your desktop and configure the variables as instructed in the file
7) then do the following

a) `Git add .` 
b) `git commit -am"..."`
c)` bash tools/init.sh`
d) `git push`

**Expected behavior**

I am supposed to get something as similar as https://chirpy.cotes.info/
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: Version 81.0.4044.122 (Official Build) (64-bit)

This is in incognito mode

![Capture](https://user-images.githubusercontent.com/63347261/80409151-a4ec2e80-88c8-11ea-9312-963ee7258719.PNG)

**Comment by cotes2020** [comment]
This is because you do not configure site variables correctly:

https://github.com/magedhelmy1/web/blob/76abba68f4e9d8344d63fd829a77c051a74c02ee/_config.yml#L21)

https://github.com/magedhelmy1/web/blob/76abba68f4e9d8344d63fd829a77c051a74c02ee/_config.yml#L49

It is recommended that you first learn about the two types of GitHub Pages Site:
<https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites>

**Comment by magedhelmy1** [comment]
Thank you, I have an idea for adding simple instructions, will submit a pull request. Thanks again.
