### ISSUE TITLE
Resolve correct image depending on active theme

### ISSUE THREAD

**Issue by Periecle** [cotes2020/jekyll-theme-chirpy#481]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I have a lot of images that look great on the light theme, but on the dark theme look awful or vice versa.

## Describe the solution you'd like

It would be great to specify different images depending on a currently selected theme.

If the theme for the image is unspecified, then behavior remains unchanged. Otherwise, the correct image should be resolved and rendered.

## Describe alternatives you've considered

Currently, I don't know alternative solutions. 

## Additional context

![image](https://user-images.githubusercontent.com/26135126/148687289-f57b46d0-38b5-4079-b485-30ae83bc8381.png)
![image](https://user-images.githubusercontent.com/26135126/148687301-c83627b3-358b-4592-a260-def0e96e76e7.png)

**Comment by digitigradeit** [comment]
Head over to the live mermaid editor 

https://mermaid-js.github.io/mermaid-live-editor/edit

and you should be able to re-create these diagrams using mermaid. if you use the built-in mermaid refactoring done by chirpy, it will auto-switch from dark/light since mermaid is svg base and the mode can be passed down before the svg is rendered.

in my own testing, using a plugin like Jekyll-spaceship which has its own mermaid processor and then generates a static image that's then included before the post is converted to html (by default) , it does not have the same auto-switch method for dark/light mode.

how many is a lot of images? I am mot sure if it makes sense to re-create them by hand or not. what did you use to generate the images the first time?

**Comment by cotes2020** [comment]
There are currently three methods:

1. The easiest way is to add a black background color to the image suitable for dark mode, and vice versa.
2. As @digitigradeit  mentioned, redraw the images with _Mermaid_
3. Redesign the colors of images to make them look great in both night and day modes. 
    
   For instance:

   ![](https://cdn.jsdelivr.net/gh/cotes2020/blog-images@8d34b77bab798e803cd6b70c6c484014d4d3bd9a/2102010/release-branches.svg)

**Comment by Periecle** [comment]
Ok, that makes sense. Thank you
