### ISSUE TITLE
Can't see Last Posts Info

### ISSUE THREAD

**Issue by mindlabcore** [cotes2020/jekyll-theme-chirpy#6]
Hi, I can't see last posts info column on my right side pannel, what's wrong? I run bash init.sh already. 
My repo: https://github.com/virgulco/virgulco.github.io Live: https://virgul.co

![image](https://user-images.githubusercontent.com/44535256/66249587-5d406280-e73e-11e9-81d4-06f50e466871.png)

Thank you for your kindly support.

**Comment by cotes2020** [comment]
I took a look at the contents of your blog repository and found that `init.sh` is an old version that did not trigger the last updated script.

To solve this problem, update the following files of template:

- `_scripts`  (Python3.5 or above is required)
- `init.sh`

In additional, the `run.sh` and `build.sh` should be updated, too.

**Comment by mindlabcore** [comment]
You are such a amazing! Thank you!

**Comment by cotes2020** [comment]
**The `mktemp` command**

I wrote the bash scripts with GUN/Linux environment (althought my machine is MacBook Pro), so they haven't been tested on Mac's original `mktemp` command before. Thanks for report this problem.

The argument `-t` of command `mktemp` holds different meaning bettween Darwin(macOS) and GUN/Linux. So just simply remove the `-t` options, the tool scripts in this project will work well on Mac and Linux.

Fixed at: 3540feb32514984e34c195e68cf8b6b4fe30cdde


**Why the Lastmod of Posts still not shown**

The other template code of your project is not updated, which I didn't notice that yesterday. So that the **lastmod** of posts still not shown on your site.

The lastmod list implemented here:
<https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_includes/panel.html#L11>

Due to the project code has been updated a lot since the day you cloned it, to reduce other unnecessary problems in the future, please update all other parts of the template code.

**Comment by mindlabcore** [comment]
Thanks a lot!
