### ISSUE TITLE
How to add subtitle to a post

### ISSUE THREAD

**Issue by sati-bodhi** [cotes2020/jekyll-theme-chirpy#615]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

How do I add a subtitle to the post?

I am using [jekyll-org](https://github.com/eggcaker/jekyll-org) in place of the regular markdown format. Just as what would be done with `yml`, I have added a `#+SUBTITLE:` to my front-matter. 

In `jekyll-theme-chirpy-5.2.0/_layouts`, I find:

```liquid
    {% if page.layout == 'page' or page.collection == 'tabs'%}
      {% assign title = site.data.locales[lang].tabs[tab_key] | default: page.title %}
      <h1 class="dynamic-title">
        {{ title }}
      </h1>
      <div class="post-content">
        {{ _content }}
      </div>
    {% else %}
      {{ _content }}
    {% endif %}
```
I suppose I would need to manually inject `liquid` code like the one below, somewhere under the `<h1>` tag in the template above:

```liquid
{% if page.subtitle %}
    <p id="page-subtitle" class="page__subtitle p-name" itemprop="headline">
    {{ page.subtitle }}
    </p>
{% endif %}
```
But (a) I don't know the right way to do this and (b) I don't want to hack the source code.

**Comment by lnfel** [comment]
1. Make a `_layouts` directory in your project root folder.
2. Create a file with the same name of the layout you want to override. In this case you would want to make `_layouts/post.html`.
3. Copy all the contents of `jekyll-theme-chirpy-5.2.0/_layouts/post.html` to your newly created `_layouts/post.html`.
4. In your font matter, add the `subtitle` variable (I suggest to make it lowercase as it is the convention on naming this kind of variable) just like the following:
```
---
title: Comprehensive guide to Laravel Deployment using PHP Deployer
date: 2022-07-29 08:57:00 PM
categories: [Laravel, Deployment]
tags: [php, server, automation]     # TAG names should always be lowercase
subtitle: I love pizza but this has nothing to do with deployment
---
```
5. Finally you can access the variable via `page.subtitle`, add it to `_layouts/post.html` using liquid like the following:
```
---
layout: page
refactor: true
pannel_includes:
  - toc
tail_includes:
  - related-posts
  - post-nav
  - comments
---

{% include lang.html %}

<h1 data-toc-skip>{{ page.title }}</h1>
<p>{{ page.subtitle }}</p>
```
This is the correct way of extending layouts in Jekyll. With this you don't need to override Chirpy's own `post.html` layout since you are just simply adding on top of it. This way you can change anything you want in your layout without requesting for new features or changes on Chirpy theme. I hope this helps.
