### ISSUE TITLE
Syntax highlighting and line number issue

### ISSUE THREAD

**Issue by zeeshankhan** [cotes2020/jekyll-theme-chirpy#66]
Hi, This repository is amazing and on first glance I loved it.
Thanks a ton to all who contributed and developed. ❤️ 

I'm an iOS engineer and starting to blog about Swift and multiplateform Kotlin stuff.
I was trying to add code highlight but it is not showing up for some reason.

My code block appears to be normal, neither line number or syntax highlight appears. when I remove `Swift` or `Kotlin`, it shows line number but with no syntax highlighting.

I went through this post to see if I'm doing anything wrong, but could not notice it.
https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_posts/2019-08-08-write-a-new-post.md#specific-language

I also went through Jekyll post about the same: https://jekyllrb.com/docs/liquid/tags/#stylesheets-for-syntax-highlighting
and was wondering if I need to do any changes to css files.

Please let me know, if I need to install any other plugin or requires some changes in CSS file.

With `Swift` name
<img width="453" alt="Screen Shot 2020-05-29 at 11 35 27 AM" src="https://user-images.githubusercontent.com/373262/83233945-8cf61c00-a1a0-11ea-9409-2a1231412e77.png">

Without any language name
<img width="472" alt="Screen Shot 2020-05-29 at 11 35 07 AM" src="https://user-images.githubusercontent.com/373262/83233960-94b5c080-a1a0-11ea-8df4-3515f8b8a9d7.png">

Blog: https://zeeshankhan.github.io/
Github: https://github.com/zeeshankhan/zeeshankhan.github.io

Thanks a lot :)
Have a great day!

**Comment by cotes2020** [comment]
> With `Swift` name

Why not lower case?

**Comment by zeeshankhan** [comment]
![giphy](https://user-images.githubusercontent.com/373262/83236409-8b2e5780-a1a4-11ea-946e-644d846921ee.gif)

**Comment by zeeshankhan** [comment]
Thank you, that worked.

**Comment by yarkhinephyo** [comment]
Hi,

Thank you for this repository :) I am facing a similar issue as above where syntax highlighting and line numbers do not appear. But my letters are in the correct lowercase.

Blog (Sample page): https://yarkhinephyo.github.io/posts/async-io-event-loop/
Github: https://github.com/yarkhinephyo/yarkhinephyo.github.io

On inspecting with devtools, it seems that [`_sass/addon/syntax.scss`](https://github.com/cotes2020/jekyll-theme-chirpy/blob/b7ad538ce2d4db5409778bbfb43c8edc456cb924/_sass/addon/syntax.scss) file is added to the webpage but the import of `light-syntax.scss` is not. Maybe that's why font-sizes and formatting look okay but the colors are not there.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/b7ad538ce2d4db5409778bbfb43c8edc456cb924/_sass/addon/syntax.scss#L12

I was wondering if this is a bug or I am doing something wrong for the formatting to fail.

Thank you!
