### ISSUE TITLE
Support for Ads / Google AdSense

### ISSUE THREAD

**Issue by acdoussan** [cotes2020/jekyll-theme-chirpy#669]
## Checklist

- [ x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [ x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x ] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [ x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I'd like to monetize my blog and inject some non-intrusive ads at the end of a post, and maybe on the sidebar of a post under the trending tags. Are there any easy hooks into the HTML for me to do this, or would this require some editing of the main package, probably with some new config options?

## Describe the solution you'd like

Ideally, it would just be some config items for google AdSense, similar to the google analytics items.

## Describe alternatives you've considered

Searched through the code base and did not see any obvious hooks to inject anything.

**Comment by kausar007** [comment]
I managed to inject code using inheritance of Jekyll. However this feature would be nice. 

The way I did it was to create two folders in my project called `_layouts` and `_includes`. 

Under `_includes` folder I created one file called `advertisement.html`. This is where the adsense code goes. In the `_layouts` folder create a file for your own post layout. For example I call it mypost.html. This is what mypost.html looks like:

```
---
layout: post
---

{{ content }}

{% include advertisement.html %}

```
 
This basically gets the content of the themes post layout and then appends the advertisement.html to bottom.

Now in articles instead of using `layout: post` I just use `layout: mypost`

**Comment by acdoussan** [comment]
I have some pending changes to implement this, but have been blocked with getting onboarded to google ads due to not enough content, working on that and will hopefully have an experimental change to test soon.

**Comment by AhmedElwerdany** [comment]
@kausar007 AdSense requires you to add `ads.txt` file in the root of your domain. 
how can you do that? , since `chirpy` only works on the `baseurl` with the name of the repo

```yml
# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: '/blog'
```

my blog only works on https://ahmedelwerdany.github.io/blog/
how can you deal with that?
