### ISSUE TITLE
More toc levels

### ISSUE THREAD

**Issue by PoeticGenius** [cotes2020/jekyll-theme-chirpy#761]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I have four sections in my post. And the theme can only display the first two. I want to display all of them.

```
# Section 1

Text here

## Section 1.1

Text here

### Section 1.2

Text here

#### Section 1.3

Text here

```

## Describe the solution you'd like

Maybe we can control toc level for post. For instance, you may find [this plugin](https://github.com/toshimaru/jekyll-toc#toc-levels) useful.

**Comment by NichtsHsu** [comment]
I am not the author of the theme but I can answer some questions.

1. Chirpy is using [bootstrap-toc](https://afeld.github.io/bootstrap-toc/) now, which can only be used to generate second-level navigation.
2. Your metioned plugin [toshimaru/jekyll-toc](https://github.com/toshimaru/jekyll-toc) should not be an alternative, because Github Pages will prevent you from using jekyll plugins other than [this list](https://pages.github.com/versions/).
3. As an alternative, you may use the pure liquid solution [allejo/jekyll-toc](https://github.com/allejo/jekyll-toc).
