### ISSUE TITLE
SASS variables not being overwritten

### ISSUE THREAD

**Issue by Caier** [cotes2020/jekyll-theme-chirpy#827]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

sass variables not being overwritten, despite creating a `_sass/variables-hook.scss` file

### To Reproduce

1. Create your blog from the Chirpy Starter template and `git clone` the freshly created repository.
2. Create a `_sass` directory and a `variables-hook.scss` file inside it.
3. Put this content inside the file: 
```scss
$sidebar-width-large: 300px;
$tab-count: 2;
```
4. Run the local server using the `bundle exec jekyll s` command.
5. Visit `localhost:4000` and notice that the sidebar's width is still 350px, not 300, and the tab-count is still 5, not 2.

### Expected behavior

The sidebar's width should be 300px and there should be 2 tabs visible on it.

### Screenshots

Assumed location of the variables-hook file:
![image](https://user-images.githubusercontent.com/16463378/209896327-0b6c0929-1153-4d84-8e79-57bd9e087df9.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |   3.0.4p208      |
| `gem -v`                          |   3.3.15      |
| `bundle -v`                       |     2.4.1    |
| `bundle exec jekyll -v`           |   4.3.1      |
| `bundle info jekyll-theme-chirpy` |    5.4.0     |

**Comment by NichtsHsu** [comment]
I believe this is a `chirpy-starter` issue, since the `variables-hook.scss` works well in `jekyll-theme-chirpy`.

To temporarily solve this issue, you can download the file [`_sass/jekyll-theme-chirpy.scss`](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_sass/jekyll-theme-chirpy.scss) into your own repo.

It is worth mentioning that the variable `$tab-count` is only used for backward compatible. If you want to change the count of tabs, you'd better to add or remove markdown files under `_tab` folder and adjust their `order` property.
