### ISSUE TITLE
Build failed because of ruby version

### ISSUE THREAD

**Issue by create3000** [cotes2020/jekyll-theme-chirpy#831]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

Build of website on GitHub failed because of ruby version. Below output of Action:

```
Run cd ./docs && bundle install && bundle exec jekyll b
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Could not find compatible versions

Because jekyll-theme-chirpy >= 5.4.0 depends on Ruby >= 2.5, < 3.2
  and Gemfile depends on jekyll-theme-chirpy >= 5.4.0, < 6.A,
  Ruby >= 2.5, < 3.2 is required.
So, because current Ruby version is = 3.2.0,
  version solving has failed.

Error: Process completed with exit code 6.
```

Ruby version is set here:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/7887b5ab62ca37094f31c37b488d55b3afd9bcb1/jekyll-theme-chirpy.gemspec#L26

### Expected behavior

Website should build.

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |    gihub     |
| `gem -v`                          |    GitHub     |
| `bundle -v`                       |    GitHub     |
| `bundle exec jekyll -v`           |    GitHub     |
| `bundle info jekyll-theme-chirpy` |    GitHub     |

**Comment by stuartw1** [comment]
I got this to work when used with the template starter repo by adding an equals sign before 3.2
`
spec.required_ruby_version = [">= 2.5", "<= 3.2"] `

I would submit a PR, but the test script appears to fail and I am not sure I have time to debug.

If you want a quick fix, you can fork this repo and apply the change.

You can then use something like the following gemfile if using the starter repo (replace <GITHUB-USERNAME> with your username). I had to hold back protobuf and nokogiri too, as they are stuck on 3.2dev with the same issue, though this is probably a bad idea long term.

You will probably want to switch back to the main one at some point, after the issue is resolved

`
# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll-theme-chirpy", :git => "https://github.com/<GITHUB-USERNAME>/jekyll-theme-chirpy.git"

group :test do
  gem "html-proofer", "~> 3.18"
end

gem "google-protobuf", "~> 3.21","<= 3.21.8"
gem "nokogiri","~> 1.13", "<= 1.13.9"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

# Jekyll <= 4.2.0 compatibility with Ruby 3.0
gem "webrick", "~> 1.7"

`

**Comment by stuartw1** [comment]
Update: I got further and everything appeared to build ok on github pages, but the site didn't work when deployed

The underlying issue appears to be a problem with liquid-4.0.3 and jekyll. 

https://github.com/jekyll/jekyll/issues/9231

I guess my plan is probably to wait for that to resolve (or GitHub to use older Ruby or something) and do something else for a few days rather than messing with the libraries

**Comment by create3000** [comment]
I finally got it working. There is a possibility to set the ruby version in the action. This is already done in the starter where version is 3.1.

**Comment by jmcbri** [comment]
Should the gemspec be updated to at least allow for a ruby version that is not end-of-life?  I'm not much of a coder, but I think I could do a PR that does that.
