### ISSUE TITLE
page successfully builds but doesn't display question

### ISSUE THREAD

**Issue by gonzoknows** [cotes2020/jekyll-theme-chirpy#859]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Why does this sometimes happen, when I go to build my page it succeeds on building but sometimes shows a blank page with the words "--- layout: home # Index page ---". Then I always have to go back and rerun the workflow. Anyone got any solutions?

![Screenshot from 2023-01-14 23-35-12](https://user-images.githubusercontent.com/122128828/212528693-1d080f77-93c9-4b3e-a3a1-5884481671d6.png)
![Screenshot from 2023-01-14 23-35-25](https://user-images.githubusercontent.com/122128828/212528697-9357717e-daba-4cc2-81f4-4d7ee8a53817.png)

**Comment by p-kostic** [comment]
I'm encountering the same issue. Although re-running the `Build and Deploy` flow manually correctly builds and deploys to GitHub Pages.

It seems that the `Build and Deploy` workflow doesn't get triggered automatically for every type of change (e.g. Updating README.md). The name of the workflow run will be that of the commit message.

If, however, `pages-build-deployment` gets triggers without the previous run being present, you'll get an empty index page similar to the image @gonzoknows reports.

I initially thought this made sense. If no re-build is necessarily required for the live website (e.g. only editing readme.md), we refer to the previous artifact. Thus not having the need to run that workflow. The site hasn't changed. 

However, something seems to go wrong here. `/.github/workflows/pages-deploy.yml` only contains the `Build and Deploy` workflow. I generated my repo from the starter template. Where does the `pages-build-deployment` workflow come from? 

What happens if I delete this workflow? 

Before experimenting in my live environment, I'll wait for a response here from the maintainer of the repo. I don't have enough experience with GitHub Actions anyways.

In the meantime, manually triggering the workflow seems to work.

**Comment by Printeger** [comment]
same here

**Comment by laolaolulu** [comment]
github pages ......

**Comment by galenseilis** [comment]
Manually triggering the workflow did not seem to work for me.

**Comment by Printeger** [comment]
> Manually triggering the workflow did not seem to work for me.

you can try this. it works for me.
https://github.com/cotes2020/jekyll-theme-chirpy/issues/853#issuecomment-1420279583
